import { request, type ApiEnvelope } from "../utils/request";

export type Announcement = { title: string; content: string };
export type Agreement = { title: string; content: string };
export type Branding = { platform_name: string; site_id: number | null; site_name: string };
export type RuleSettings = {
  title: string;
  basic: string;
  special: string;
  amount: string;
  text: string;
  content?: string;
};
export type UserProfile = {
  balance: string;
  total_balance: string;
  credit_balance: string;
  used_balance: string;
  available_balance: string;
};
export type Lottery = {
  id: number;
  name: string;
  code: string;
  sort: number;
  latest_code: string;
  latest_numbers: string;
  next_code: string;
  next_open_time: string | null;
  can_bet?: boolean;
};
export type AgentLineOption = { url: string; line: number };
export type InitialCredential = { id: number; username: string; initial_password: string; must_change_password: number };
export type OrganizationLevel = "director" | "shareholder" | "small_shareholder" | "general_agent" | "agent";
export type AgentCreditSummary = {
  granted_credit: string;
  current_available_balance: string;
  direct_child_credit: string;
  direct_member_credit: string;
  unassigned_member_credit: string;
  unassigned_member_net_score: string;
  unassigned_member_settlement_change: string;
  credit_unallocated: boolean;
  credit_notice: string;
  total_credit: string;
  available_credit: string;
  allocated_credit: string;
};
export type AgentOrganizationProfile = { site: { id: number; name: string }; organization: { id: number; name: string; level: OrganizationLevel; level_label: string; next_level: OrganizationLevel | null; credit: AgentCreditSummary } | null; permissions: string[]; username: string };
export type AgentOrganizationNode = { id: number; parent_id: number; name: string; code: string; level: OrganizationLevel; level_label: string; next_level: OrganizationLevel | null; credit_limit: string; balance?: string; permissions: string[]; status: number; account_id?: number | null; username?: string | null; display_name?: string | null; phone?: string | null; online?: number; last_login_at?: string | null; last_login_ip?: string | null; last_login_location?: string | null; last_login_device?: string | null; share_rate?: string; max_share_rate?: string; child_count?: number };
export type AgentProfitShare = { child_organization_id: number; parent_organization_id: number; share_rate: string; max_share_rate: string };
export type AgentOrganizationAccount = { id: number; organization_id: number; username: string; display_name: string; phone?: string; permissions: string[]; status: number; online?: number; last_login_at?: string; last_login_ip?: string; last_login_location?: string };
export type OrganizationCatalog = { levels: Array<{ value: OrganizationLevel; label: string }>; permissions: Array<{ code: string; label: string }> };
export type AgentOrganizationMember = { id: number; organization_id: number; username: string; display_name: string; phone?: string | null; balance: string; credit_balance: string; used_balance: string; available_balance: string; status: number; online?: number; last_login_at?: string | null; last_login_ip?: string | null; last_login_location?: string | null; created_at?: string | null };
export type AgentOrganizationBreadcrumb = { id: number; name: string; level: OrganizationLevel; level_label: string };
export type AgentOrganizationList = { current: { id: number; parent_id: number; name: string; node_name?: string; level: OrganizationLevel; level_label: string; next_level: OrganizationLevel | null; credit: AgentCreditSummary; permissions?: string[]; can_manage?: boolean }; root_organization_id: number; breadcrumbs: AgentOrganizationBreadcrumb[]; site_max_share_rate: string; nodes: AgentOrganizationNode[]; members?: AgentOrganizationMember[]; accounts: AgentOrganizationAccount[]; catalog: OrganizationCatalog };
export type MemberLotteryPermission = { lottery_id: number; name: string; code: string; can_view: boolean; can_bet: boolean; offline_rebate: string };
export type MemberLotteryOdds = {
  id: number;
  lottery_id: number;
  lottery_name: string;
  lottery_code: string;
  category: string;
  name: string;
  min_bet: string;
  odds_limit: string;
  single_bet_limit: string;
  single_item_limit: string;
  odds: string;
  offline_rebate: string;
  direct_category?: number;
};
export type AgentMember = {
  id: number;
  username: string;
  display_name: string;
  phone: string | null;
  balance: string;
  credit_balance: string;
  used_balance: string;
  available_balance: string;
  status: number;
  remark?: string | null;
  account_state?: "enabled" | "disabled" | "bet_paused";
  interception_rate?: string;
  type: string;
  last_login_at: string | null;
  last_login_ip?: string | null;
  last_login_location?: string | null;
  created_at: string | null;
  permissions?: MemberLotteryPermission[];
  odds?: MemberLotteryOdds[];
  summary?: AgentCreditSummary;
};
export type AgentMemberList = {
  list: AgentMember[];
  total: number;
  page: number;
  page_size: number;
  total_credit: string;
  available_credit: string;
  allocated_credit: string;
} & Partial<AgentCreditSummary>;

export const getAnnouncement = () => request.get<ApiEnvelope<Announcement>>("/agent/announcement");
export const getBranding = () => request.get<ApiEnvelope<Branding>>("/branding");
export const getAgreement = () => request.get<ApiEnvelope<Agreement>>("/agent/agreement");
export const getRules = (params?: Record<string, unknown>) => request.get<ApiEnvelope<RuleSettings>>("/agent/rules", { params });
export const getProfile = () => request.get<ApiEnvelope<UserProfile>>("/user/profile");
export const getLotteries = () => request.get<ApiEnvelope<{ list: Lottery[] }>>("/agent/lotteries");
export const getAgentLineOptions = () => request.get<ApiEnvelope<{ list: AgentLineOption[] }>>("/agent/line-options");
export const getAgentOrganizationProfile = () => request.get<ApiEnvelope<AgentOrganizationProfile>>("/agent/profile");
export const getAgentOrganizations = (params?: { organization_id?: number }) => request.get<ApiEnvelope<AgentOrganizationList>>("/agent/organizations", { params });
export const createAgentOrganization = (payload: Record<string, unknown>) => request.post<ApiEnvelope<InitialCredential & { node_id: number }>>("/agent/organizations", payload);
export const updateAgentOrganization = (id: number, payload: Record<string, unknown>) => request.put<ApiEnvelope<null>>(`/agent/organizations/${id}`, payload);
export const deleteAgentOrganization = (id: number) => request.delete<ApiEnvelope<null>>(`/agent/organizations/${id}`);
export const createAgentOrganizationAccount = (organizationId: number, payload: Record<string, unknown>) => request.post<ApiEnvelope<InitialCredential>>(`/agent/organizations/${organizationId}/accounts`, payload);
export const updateAgentOrganizationAccount = (id: number, payload: Record<string, unknown>) => request.put<ApiEnvelope<null>>(`/agent/organization-accounts/${id}`, payload);
export const deleteAgentOrganizationAccount = (id: number) => request.delete<ApiEnvelope<null>>(`/agent/organization-accounts/${id}`);
export const getAgentProfitShares = () => request.get<ApiEnvelope<AgentProfitShare[]>>('/agent/profit-shares');
export const saveAgentProfitShare = (childId: number, payload: { share_rate: number; max_share_rate: number }) => request.put<ApiEnvelope<AgentProfitShare>>(`/agent/profit-shares/${childId}`, payload);
export const getAgentMembers = (params: Record<string, unknown>) => request.get<ApiEnvelope<AgentMemberList>>("/agent/members", { params });
export const getAgentMember = (id: number) => request.get<ApiEnvelope<AgentMember>>(`/agent/members/${id}`);
export const createAgentMember = (payload: Record<string, unknown>) => request.post<ApiEnvelope<InitialCredential>>("/agent/members", payload);
export const updateAgentMember = (id: number, payload: Record<string, unknown>) => request.put<ApiEnvelope<null>>(`/agent/members/${id}`, payload);
export type AuditLog = { id: number; username: string | null; action: string; resource?: string | null; ip?: string | null; created_at: string; target_username?: string; content?: string; before_value?: string; after_value?: string; device?: string };
export type AuditLogList = { list: AuditLog[]; total: number; page: number; page_size: number };
export const getAuditLogs = (params: Record<string, unknown>) => request.get<ApiEnvelope<AuditLogList>>('/agent/audit-logs', { params });
export type LedgerRow = { label: string; category: string; bet_count: number; amount: string; rebate: string; offline_water: string; win_amount: string; profit: string };
export type ContributionRow = { member: string; share_amount: string; share_total_amount: string; share_total_profit: string; offline_water: string; percentage_share_profit: string; actual_share_profit: string; share_percentage: string; contribution: string };
export type LedgerIssue = { issue_no: string; date: string };
export const getLedger = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: Array<LedgerRow|ContributionRow>; total: number }>>('/agent/ledger', { params });
export const getLedgerIssues = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: LedgerIssue[] }>>('/agent/ledger/issues', { params });
export type ResultRow = { issue_no: string; draw_time: string; numbers: string; sum_value?: number|null; size?: string|null; parity?: string|null; span_value?: number|null; pending?: number };
export const getResults = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: ResultRow[] }>>('/agent/results', { params });
export type AgentSettingProfile = { username: string; display_name: string; remark: string; share_limit: string; follow_share: number; total_credit: string; allocated_credit: string; available_credit: string; organization_level: OrganizationLevel | ""; interception_editable: number; interception_notice: string };
export type AgentSettingOdds = { id: number; lottery_id: number; category_id: number; category: string; name: string; min_bet: string | null; odds_limit: string | null; single_bet_limit: string | null; single_item_limit: string | null; interception_amount: string; direct_category?: number };
export type AgentSettingsData = { profile: AgentSettingProfile; lottery: { id: number; name: string; code: string }; odds: AgentSettingOdds[] };
export const getAgentSettings = (params: Record<string, unknown>) => request.get<ApiEnvelope<AgentSettingsData>>('/agent/settings', { params });
export const saveAgentSettings = (payload: { lottery: string; amounts: Record<string, string>; follow_share: number }) => request.put<ApiEnvelope<{ amounts: Record<string,string>; follow_share: number }>>('/agent/settings', payload);
export type AgentReportMetrics = { bet_count: number; amount: string; win_amount: string; water: string; member_profit: string; share_amount: string; share_profit: string; offline_water: string; agent_water: string; agent_profit: string; platform_amount: string; platform_profit: string };
export type AgentMonthlyReportRow = { issue_no: string; draw_date: string; summary: AgentReportMetrics };
export const getAgentReport = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ summary: AgentReportMetrics }>>('/agent/reports', { params });
export const getAgentMonthlyReport = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: AgentMonthlyReportRow[]; total: AgentReportMetrics }>>('/agent/reports/monthly', { params });
export type AgentReportIssue = { issue_no: string; date: string };
export const getAgentReportIssues = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: AgentReportIssue[] }>>('/agent/reports/issues', { params });
export type InterceptionIssue = { issue_no: string; date: string };
export type InterceptionCategory = { id: number; category: string; name: string; odds: string; sort: number };
export type InterceptionRow = { id: number; order_no: string; issue_no: string; member: string; placed_at: string; number: string; category: string; bet_amount: string; share_rate: string; intercepted_amount: string; odds: string; rebate: string; win_amount: string; profit: string; source: string; device: string; status: string };
export type InterceptionSummary = { bet_amount: string; intercepted_amount: string; rebate: string; win_amount: string; profit: string };
export type InterceptionPlateItem = { odds_id: number; name: string; odds: string; limit: string; used: string; remaining: string; numbers: Array<{ number: string; used: string; remaining: string }> };
export type InterceptionPlateGroup = { category: string; items: InterceptionPlateItem[] };
export const getInterceptionIssues = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: InterceptionIssue[] }>>('/agent/interceptions/issues', { params });
export const getInterceptionCategories = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: InterceptionCategory[] }>>('/agent/interceptions/categories', { params });
export const getInterceptions = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: InterceptionRow[]; total: number; summary: InterceptionSummary }>>('/agent/interceptions', { params });
export const getInterceptionPlate = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ issue_no: string; groups: InterceptionPlateGroup[] }>>('/agent/interceptions/plate', { params });
export type AgentSubaccount = { id: number; username: string; display_name: string; status: number; last_login_at: string | null; last_login_ip?: string | null; last_login_location?: string | null; created_at: string; permissions?: string[]; lottery_permissions?: number[]; report_limit_enabled?: number; report_from_issue?: string | null; report_to_issue?: string | null };
export type AgentSubaccountOption = { key: string; label: string };
export type AgentSubaccountLottery = { id: number; name: string; code: string };
export type AgentSubaccountIssue = { issue_no: string; date: string };
export type AgentSubaccountPayload = { username: string; display_name: string; password?: string; status: number; permissions: string[]; lottery_permissions: number[]; report_limit_enabled: number; report_from_issue: string; report_to_issue: string };
export const getAgentSubaccounts = (params: Record<string, unknown>) => request.get<ApiEnvelope<{ list: AgentSubaccount[]; total: number; page: number; page_size: number }>>('/agent/subaccounts', { params });
export const getAgentSubaccount = (id: number) => request.get<ApiEnvelope<AgentSubaccount>>(`/agent/subaccounts/${id}`);
export const getAgentSubaccountOptions = () => request.get<ApiEnvelope<{ permissions: AgentSubaccountOption[]; lotteries: AgentSubaccountLottery[]; issues: AgentSubaccountIssue[] }>>('/agent/subaccounts/options');
export const createAgentSubaccount = (payload: AgentSubaccountPayload) => request.post<ApiEnvelope<InitialCredential>>('/agent/subaccounts', payload);
export const updateAgentSubaccount = (id: number, payload: AgentSubaccountPayload) => request.put<ApiEnvelope<null>>(`/agent/subaccounts/${id}`, payload);
export const deleteAgentSubaccount = (id: number) => request.delete<ApiEnvelope<null>>(`/agent/subaccounts/${id}`);
export const batchDeleteAgentSubaccounts = (ids: number[]) => request.post<ApiEnvelope<{ count: number }>>('/agent/subaccounts/batch-delete', { ids });
