<?php
use think\facade\Route;
Route::group('api/v1', static function () {
    Route::get('health', 'Health/index');
    Route::post('admin/auth/login', 'Auth/adminLogin');
    Route::post('admin/auth/logout', 'Auth/logout');
    Route::get('admin/auth/menus', 'Auth/menus');
    Route::post('user/auth/login', 'Auth/userLogin');
    Route::get('user/auth/captcha', 'Auth/captcha');
    Route::post('user/auth/captcha/verify', 'Auth/verifyCaptcha');
    Route::post('agent/auth/login', 'Auth/agentLogin');
    Route::get('agent/auth/captcha', 'Auth/captcha');
    Route::post('agent/auth/captcha/verify', 'Auth/verifyCaptcha');
    Route::get('agent/agreement', 'SiteSettings/agentAgreement');
    Route::get('agent/announcement', 'SiteSettings/agentAnnouncement');
    Route::get('agent/rules', 'SiteSettings/agentRules');
    Route::get('agent/lotteries', 'Lottery/agent');
    Route::get('agent/members/:id', 'AgentMember/detail');
    Route::put('agent/members/:id', 'AgentMember/update');
    Route::get('agent/members', 'AgentMember/index');
    Route::post('agent/members', 'AgentMember/create');
    Route::get('agent/report-categories', 'AgentBusiness/categories');
    Route::get('agent/order-details', 'AgentBusiness/orderDetails');
    Route::get('agent/winning-details', 'AgentBusiness/winningDetails');
    Route::get('agent/bet-records', 'AgentBusiness/betRecords');
    Route::get('agent/refunds', 'AgentBusiness/refunds');
    Route::get('user/agreement', 'SiteSettings/userAgreement');
    Route::get('user/profile', 'Auth/userProfile');
    Route::post('user/auth/password', 'Auth/changeUserPassword');
    Route::get('user/announcement', 'SiteSettings/userAnnouncement');
    Route::get('user/rules', 'SiteSettings/userRules');
    Route::get('user/lotteries', 'Lottery/user');
    Route::get('user/line-options', 'UserBusiness/lineOptions');
    Route::get('user/bet-records', 'UserBusiness/betRecords');
    Route::post('user/bet-records/:id/refund', 'UserBusiness/refundBetRecord');
    Route::get('user/stop-drops', 'UserBusiness/stopDrops');
    Route::get('user/bet-details', 'UserBusiness/betDetails');
    Route::get('user/bills', 'UserBusiness/bills');
    Route::get('user/draws', 'UserBusiness/draws');
    Route::get('user/draws/wait', 'UserBusiness/waitDraws');
    Route::post('user/quick-entry/preview', 'UserBusiness/quickPreview');
    Route::post('user/quick-entry/place', 'UserBusiness/quickPlace');
    Route::get('user/quick-entry/settings', 'UserBusiness/quickSettings');
    Route::put('user/quick-entry/settings', 'UserBusiness/saveQuickSettings');
    Route::post('user/quick-entry/tags', 'UserBusiness/createQuickTag');
    Route::delete('user/quick-entry/tags/:id', 'UserBusiness/deleteQuickTag');
    // Hyphenated resource names need explicit routes because the dynamic
    // segment parser treats the hyphen as a separator.
    Route::get('admin/sub-agents', 'Resource/index')->append(['resource' => 'sub-agents']);
    Route::post('admin/sub-agents', 'Resource/create')->append(['resource' => 'sub-agents']);
    Route::put('admin/sub-agents/:id', 'Resource/update')->append(['resource' => 'sub-agents']);
    Route::delete('admin/sub-agents/:id', 'Resource/delete')->append(['resource' => 'sub-agents']);
    Route::get('admin/audit-logs', 'Resource/index')->append(['resource' => 'audit-logs']);
    Route::get('admin/agent-center/:id/enter', 'Auth/adminEnter');
    Route::get('admin/agent-center', 'Resource/index')->append(['resource' => 'agent-center']);
    Route::post('admin/agent-center', 'Resource/create')->append(['resource' => 'agent-center']);
    Route::put('admin/agent-center/:id', 'Resource/update')->append(['resource' => 'agent-center']);
    Route::delete('admin/agent-center/:id', 'Resource/delete')->append(['resource' => 'agent-center']);
    Route::get('admin/site-users', 'Resource/index')->append(['resource' => 'site-users']);
    Route::post('admin/site-users', 'Resource/create')->append(['resource' => 'site-users']);
    Route::put('admin/site-users/:id', 'Resource/update')->append(['resource' => 'site-users']);
    Route::delete('admin/site-users/:id', 'Resource/delete')->append(['resource' => 'site-users']);
    Route::get('admin/bet-records/aggregation', 'BetAggregation/index')->completeMatch();
    Route::get('admin/bet-records/aggregation-details', 'BetAggregation/details')->completeMatch();
    Route::get('admin/bet-records', 'Resource/index')->append(['resource' => 'bet-records']);
    Route::get('admin/bet-record-details/:id', 'Resource/betDetails');
    Route::put('admin/bet-details/:id', 'Resource/updateBetDetail');
    Route::get('admin/site-settings/agreement', 'SiteSettings/adminAgreement');
    Route::put('admin/site-settings/agreement', 'SiteSettings/saveAdminAgreement');
    Route::get('admin/site-settings/announcement', 'SiteSettings/adminAnnouncement');
    Route::put('admin/site-settings/announcement', 'SiteSettings/saveAdminAnnouncement');
    Route::get('admin/site-settings/agent-agreement', 'SiteSettings/adminAgentAgreement');
    Route::put('admin/site-settings/agent-agreement', 'SiteSettings/saveAdminAgentAgreement');
    Route::get('admin/site-settings/agent-announcement', 'SiteSettings/adminAgentAnnouncement');
    Route::put('admin/site-settings/agent-announcement', 'SiteSettings/saveAdminAgentAnnouncement');
    Route::get('admin/site-settings/rules', 'SiteSettings/adminRules');
    Route::put('admin/site-settings/rules', 'SiteSettings/saveAdminRules');
    Route::get('admin/site-settings/betting-controls', 'SiteSettings/adminBettingControls');
    Route::put('admin/site-settings/betting-controls', 'SiteSettings/saveAdminBettingControls');
    Route::get('admin/lotteries', 'Lottery/index')->completeMatch();
    Route::post('admin/lotteries', 'Lottery/create')->completeMatch();
    Route::get('admin/lotteries/:id/rules', 'Lottery/rules');
    Route::put('admin/lotteries/:id/rules', 'Lottery/saveRules');
    Route::put('admin/lotteries/:id/sites', 'Lottery/assign');
    Route::put('admin/lotteries/:id', 'Lottery/update');
    Route::delete('admin/lotteries/:id', 'Lottery/delete');
    Route::get('admin/lottery-config', 'Lottery/config');
    Route::put('admin/lottery-config', 'Lottery/saveConfig');
    Route::post('admin/lottery-config/test', 'Lottery/testConfig');
    Route::get('admin/lottery-history/:id', 'Lottery/history');
    Route::get('admin/lottery-odds/:id', 'Lottery/odds');
    Route::post('admin/lottery-odds/:id/categories', 'Lottery/createOddsCategory');
    Route::put('admin/lottery-odds/:id/categories/:category_id', 'Lottery/updateOddsCategory');
    Route::delete('admin/lottery-odds/:id/categories/:category_id', 'Lottery/deleteOddsCategory');
    Route::post('admin/lottery-odds/:id', 'Lottery/createOdds');
    Route::put('admin/lottery-odds/:id/:odds_id', 'Lottery/updateOdds');
    Route::delete('admin/lottery-odds/:id/:odds_id', 'Lottery/deleteOdds');
    // Explicit resource routes avoid the dynamic fallback swallowing nested
    // lottery endpoints such as /admin/lotteries/:id/rules.
    foreach (['admins', 'roles', 'menus', 'settings', 'domains', 'sites'] as $resource) {
        Route::get('admin/'.$resource, 'Resource/index')->append(['resource' => $resource]);
        Route::post('admin/'.$resource, 'Resource/create')->append(['resource' => $resource]);
        Route::put('admin/'.$resource.'/:id', 'Resource/update')->append(['resource' => $resource]);
        Route::delete('admin/'.$resource.'/:id', 'Resource/delete')->append(['resource' => $resource]);
    }
})->middleware([\app\middleware\ApiContext::class]);
