<?php
use think\facade\Route;
Route::group('api/v1', static function () {
    Route::get('health', 'Health/index');
    Route::options('health', 'Health/index');
    Route::get('branding', 'Branding/index');
    Route::get('security-policy', 'SecuritySettings/policy');
    Route::post('admin/auth/login', 'Saas.Auth/adminLogin');
    Route::post('admin/auth/logout', 'Saas.Auth/logout');
    Route::post('admin/auth/heartbeat', 'Saas.Auth/heartbeat');
    Route::get('admin/auth/menus', 'Saas.Auth/menus');
    Route::get('admin/system-settings/security', 'Saas.SecuritySettings/adminPolicy');
    Route::put('admin/system-settings/security', 'Saas.SecuritySettings/saveAdminPolicy');
    Route::get('admin/system-settings/branding', 'Saas.Branding/adminSettings');
    Route::put('admin/system-settings/branding', 'Saas.Branding/saveAdminSettings');
    Route::post('user/auth/login', 'User.Auth/userLogin');
    Route::post('user/auth/logout', 'User.Auth/logout');
    Route::post('user/auth/heartbeat', 'User.Auth/heartbeat');
    Route::get('user/auth/captcha', 'User.Auth/captcha');
    Route::post('user/auth/captcha/verify', 'User.Auth/verifyCaptcha');
    Route::post('agent/auth/login', 'Agent.Auth/agentLogin');
    Route::post('agent/auth/logout', 'Agent.Auth/logout');
    Route::post('agent/auth/heartbeat', 'Agent.Auth/heartbeat');
    Route::post('agent/auth/password', 'Agent.Auth/changeAgentPassword');
    Route::get('agent/auth/captcha', 'Agent.Auth/captcha');
    Route::post('agent/auth/captcha/verify', 'Agent.Auth/verifyCaptcha');
    Route::get('agent/profile', 'Agent.Organization/profile');
    Route::get('agent/organizations', 'Agent.Organization/agentIndex')->completeMatch();
    Route::post('agent/organizations', 'Agent.Organization/agentCreateNode')->completeMatch();
    Route::put('agent/organizations/:id', 'Agent.Organization/agentUpdateNode');
    Route::delete('agent/organizations/:id', 'Agent.Organization/agentDeleteNode');
    Route::post('agent/organizations/:organizationId/accounts', 'Agent.Organization/agentCreateAccount');
    Route::put('agent/organization-accounts/:id', 'Agent.Organization/agentUpdateAccount');
    Route::delete('agent/organization-accounts/:id', 'Agent.Organization/agentDeleteAccount');
    Route::get('agent/profit-shares', 'Agent.Organization/agentProfitShare');
    Route::put('agent/profit-shares/:childId', 'Agent.Organization/agentSaveProfitShare');
    Route::get('agent/agreement', 'Agent.SiteSettings/agentAgreement');
    Route::get('agent/announcement', 'Agent.SiteSettings/agentAnnouncement');
    Route::get('agent/rules', 'Agent.SiteSettings/agentRules');
    Route::get('agent/lotteries', 'Agent.Lottery/agent');
    Route::get('agent/line-options', 'Agent.AgentLine/options');
    Route::get('agent/members/:id', 'Agent.AgentMember/detail');
    Route::put('agent/members/:id', 'Agent.AgentMember/update');
    Route::get('agent/members', 'Agent.AgentMember/index');
    Route::post('agent/members', 'Agent.AgentMember/create');
    Route::get('agent/report-categories', 'Agent.AgentBusiness/categories');
    Route::get('agent/order-details', 'Agent.AgentBusiness/orderDetails');
    Route::get('agent/winning-details', 'Agent.AgentBusiness/winningDetails');
    Route::get('agent/bet-records', 'Agent.AgentBusiness/betRecords');
    Route::get('agent/refunds', 'Agent.AgentBusiness/refunds');
    Route::get('agent/ledger/issues', 'Agent.AgentLedger/issues');
    Route::get('agent/ledger', 'Agent.AgentLedger/index')->completeMatch();
    Route::get('agent/interceptions/issues', 'Agent.AgentInterception/issues');
    Route::get('agent/interceptions/categories', 'Agent.AgentInterception/categories');
    Route::get('agent/interceptions/plate', 'Agent.AgentInterception/plate');
    Route::get('agent/interceptions', 'Agent.AgentInterception/index')->completeMatch();
    Route::get('agent/results', 'Agent.AgentResults/index');
    Route::get('agent/reports/monthly', 'Agent.AgentReport/monthly');
    Route::get('agent/reports/issues', 'Agent.AgentReport/issues');
    Route::get('agent/reports', 'Agent.AgentReport/index')->completeMatch();
    Route::get('agent/audit-logs', 'Agent.AuditLog/index');
    Route::get('agent/settings', 'Agent.AgentSettings/index');
    Route::put('agent/settings', 'Agent.AgentSettings/save');
    Route::get('agent/subaccounts/options', 'Agent.AgentSubaccount/options');
    Route::post('agent/subaccounts/batch-delete', 'Agent.AgentSubaccount/batchDelete');
    Route::get('agent/subaccounts/:id', 'Agent.AgentSubaccount/detail');
    Route::put('agent/subaccounts/:id', 'Agent.AgentSubaccount/update');
    Route::delete('agent/subaccounts/:id', 'Agent.AgentSubaccount/delete');
    Route::get('agent/subaccounts', 'Agent.AgentSubaccount/index')->completeMatch();
    Route::post('agent/subaccounts', 'Agent.AgentSubaccount/create')->completeMatch();
    Route::get('user/agreement', 'User.SiteSettings/userAgreement');
    Route::get('user/profile', 'User.Auth/userProfile');
    Route::post('user/auth/password', 'User.Auth/changeUserPassword');
    Route::get('user/announcement', 'User.SiteSettings/userAnnouncement');
    Route::get('user/rules', 'User.SiteSettings/userRules');
    Route::get('user/lotteries', 'User.Lottery/user');
    Route::get('user/line-options', 'User.UserBusiness/lineOptions');
    Route::get('user/bet-records', 'User.UserBusiness/betRecords');
    Route::post('user/bet-records/:id/refund', 'User.UserBusiness/refundBetRecord');
    Route::get('user/stop-drops', 'User.UserBusiness/stopDrops');
    Route::get('user/bet-details', 'User.UserBusiness/betDetails');
    Route::get('user/bills', 'User.UserBusiness/bills');
    Route::get('user/draws', 'User.UserBusiness/draws');
    Route::get('user/draws/wait', 'User.UserBusiness/waitDraws');
    Route::post('user/quick-entry/preview', 'User.UserBusiness/quickPreview');
    Route::post('user/quick-entry/place', 'User.UserBusiness/quickPlace');
    Route::get('user/quick-entry/settings', 'User.UserBusiness/quickSettings');
    Route::put('user/quick-entry/settings', 'User.UserBusiness/saveQuickSettings');
    Route::post('user/quick-entry/tags', 'User.UserBusiness/createQuickTag');
    Route::delete('user/quick-entry/tags/:id', 'User.UserBusiness/deleteQuickTag');
    // Hyphenated resource names need explicit routes because the dynamic
    // segment parser treats the hyphen as a separator.
    Route::get('admin/sub-agents', 'Saas.Resource/index')->append(['resource' => 'sub-agents']);
    Route::post('admin/sub-agents', 'Saas.Resource/create')->append(['resource' => 'sub-agents']);
    Route::put('admin/sub-agents/:id', 'Saas.Resource/update')->append(['resource' => 'sub-agents']);
    Route::delete('admin/sub-agents/:id', 'Saas.Resource/delete')->append(['resource' => 'sub-agents']);
    Route::get('admin/audit-logs', 'Saas.Resource/index')->append(['resource' => 'audit-logs']);
    Route::delete('admin/audit-logs', 'Saas.Resource/clearAuditLogs')->completeMatch();
    Route::get('admin/audit-logs/:id', 'Saas.Resource/auditDetail');
    Route::get('admin/score-ledger/overview', 'Saas.ScoreLedger/overview');
    Route::get('admin/dashboard/score', 'Saas.ScoreLedger/dashboard');
    Route::put('admin/score-ledger/total', 'Saas.ScoreLedger/updateTotal');
    Route::get('admin/score-ledger/:id', 'Saas.ScoreLedger/detail');
    Route::get('admin/score-ledger', 'Saas.ScoreLedger/index')->completeMatch();
    Route::get('admin/agent-center/:id/enter', 'Saas.Auth/adminEnter');
    Route::get('admin/sites/:siteId/organizations', 'Saas.Organization/adminIndex');
    Route::post('admin/sites/:siteId/organizations', 'Saas.Organization/adminCreateNode');
    Route::put('admin/organizations/:id/credit-share', 'Saas.Organization/adminSetDirectorCreditShare');
    Route::put('admin/organizations/:id/credit', 'Saas.Organization/adminSetDirectorCredit');
    Route::put('admin/organizations/:id', 'Saas.Organization/adminUpdateNode');
    Route::delete('admin/organizations/:id', 'Saas.Organization/adminDeleteNode');
    Route::post('admin/organizations/:organizationId/accounts', 'Saas.Organization/adminCreateAccount');
    Route::put('admin/organization-accounts/:id', 'Saas.Organization/adminUpdateAccount');
    Route::delete('admin/organization-accounts/:id', 'Saas.Organization/adminDeleteAccount');
    Route::get('admin/sites/:siteId/profit-shares', 'Saas.Organization/adminProfitShare');
    Route::put('admin/sites/:siteId/profit-shares/:childId', 'Saas.Organization/adminSaveProfitShare');
    Route::get('admin/sites/:siteId/agent-permissions', 'Saas.SitePermissions/show');
    Route::put('admin/sites/:siteId/agent-permissions', 'Saas.SitePermissions/save');
    Route::get('admin/agent-center', 'Saas.Resource/index')->append(['resource' => 'agent-center']);
    Route::post('admin/agent-center', 'Saas.Resource/create')->append(['resource' => 'agent-center']);
    Route::put('admin/agent-center/:id', 'Saas.Resource/update')->append(['resource' => 'agent-center']);
    Route::delete('admin/agent-center/:id', 'Saas.Resource/delete')->append(['resource' => 'agent-center']);
    Route::get('admin/site-admins', 'Saas.Resource/index')->append(['resource' => 'site-admins']);
    Route::post('admin/site-admins', 'Saas.Resource/create')->append(['resource' => 'site-admins']);
    Route::put('admin/site-admins/:id', 'Saas.Resource/update')->append(['resource' => 'site-admins']);
    Route::delete('admin/site-admins/:id', 'Saas.Resource/delete')->append(['resource' => 'site-admins']);
    Route::get('admin/site-users', 'Saas.Resource/index')->append(['resource' => 'site-users']);
    Route::post('admin/site-users', 'Saas.Resource/create')->append(['resource' => 'site-users']);
    Route::put('admin/site-users/:id', 'Saas.Resource/update')->append(['resource' => 'site-users']);
    Route::delete('admin/site-users/:id', 'Saas.Resource/delete')->append(['resource' => 'site-users']);
    // Keep the collection route exact so `/admin/bet-records/batch-options`
    // reaches AdminBetBatch instead of being swallowed by Resource/index.
    Route::get('admin/bet-records', 'Saas.Resource/index')->append(['resource' => 'bet-records'])->completeMatch();
    Route::get('admin/bet-details/batch-options', 'Saas.AdminBetBatch/options');
    Route::put('admin/bet-details/batch-replace', 'Saas.AdminBetBatch/replace');
    Route::get('admin/bet-records/batch-options', 'Saas.AdminBetBatch/recordOptions');
    Route::post('admin/bet-records/batch-preview', 'Saas.AdminBetBatch/preview');
    Route::post('admin/bet-records/batch-apply', 'Saas.AdminBetBatch/apply');
    Route::get('admin/robots/options', 'Saas.AdminRobots/options');
    Route::get('admin/robots', 'Saas.AdminRobots/index')->completeMatch();
    Route::post('admin/robots', 'Saas.AdminRobots/create')->completeMatch();
    Route::put('admin/robots/:id', 'Saas.AdminRobots/update');
    Route::post('admin/robots/:id/status', 'Saas.AdminRobots/status');
    Route::post('admin/robots/:id/convert', 'Saas.AdminRobots/convert');
    Route::get('admin/robots/:id/history', 'Saas.AdminRobots/history');
    Route::get('admin/bet-record-details/:id', 'Saas.Resource/betDetails');
    Route::put('admin/bet-details/:id', 'Saas.Resource/updateBetDetail');
    Route::get('admin/site-settings/agreement', 'Saas.SiteSettings/adminAgreement');
    Route::put('admin/site-settings/agreement', 'Saas.SiteSettings/saveAdminAgreement');
    Route::get('admin/site-settings/announcement', 'Saas.SiteSettings/adminAnnouncement');
    Route::put('admin/site-settings/announcement', 'Saas.SiteSettings/saveAdminAnnouncement');
    Route::get('admin/site-settings/agent-agreement', 'Saas.SiteSettings/adminAgentAgreement');
    Route::put('admin/site-settings/agent-agreement', 'Saas.SiteSettings/saveAdminAgentAgreement');
    Route::get('admin/site-settings/agent-announcement', 'Saas.SiteSettings/adminAgentAnnouncement');
    Route::put('admin/site-settings/agent-announcement', 'Saas.SiteSettings/saveAdminAgentAnnouncement');
    Route::get('admin/site-settings/rules', 'Saas.SiteSettings/adminRules');
    Route::put('admin/site-settings/rules', 'Saas.SiteSettings/saveAdminRules');
    Route::get('admin/site-settings/betting-controls', 'Saas.SiteSettings/adminBettingControls');
    Route::put('admin/site-settings/betting-controls', 'Saas.SiteSettings/saveAdminBettingControls');
    Route::get('admin/lotteries', 'Saas.Lottery/index')->completeMatch();
    Route::post('admin/lotteries', 'Saas.Lottery/create')->completeMatch();
    Route::get('admin/lotteries/:id/rules', 'Saas.Lottery/rules');
    Route::put('admin/lotteries/:id/rules', 'Saas.Lottery/saveRules');
    Route::put('admin/lotteries/:id/sites', 'Saas.Lottery/assign');
    Route::put('admin/lotteries/:id', 'Saas.Lottery/update');
    Route::delete('admin/lotteries/:id', 'Saas.Lottery/delete');
    Route::get('admin/lottery-config', 'Saas.Lottery/config');
    Route::put('admin/lottery-config', 'Saas.Lottery/saveConfig');
    Route::post('admin/lottery-config/test', 'Saas.Lottery/testConfig');
    Route::get('admin/lottery-history/:id', 'Saas.Lottery/history');
    Route::put('admin/lottery-history/:id', 'Saas.Lottery/updateHistory');
    Route::post('admin/lotteries/:id/copy-odds', 'Saas.Lottery/copyOdds');
    Route::get('admin/lottery-odds/:id', 'Saas.Lottery/odds');
    Route::get('admin/lottery-boards', 'Saas.Lottery/boards');
    Route::post('admin/lottery-boards', 'Saas.Lottery/createBoard');
    Route::put('admin/lottery-boards/:id', 'Saas.Lottery/updateBoard');
    Route::post('admin/lottery-odds/:id/categories', 'Saas.Lottery/createOddsCategory');
    Route::put('admin/lottery-odds/:id/categories/:category_id', 'Saas.Lottery/updateOddsCategory');
    Route::delete('admin/lottery-odds/:id/categories/:category_id', 'Saas.Lottery/deleteOddsCategory');
    Route::post('admin/lottery-odds/:id', 'Saas.Lottery/createOdds');
    Route::put('admin/lottery-odds/:id/:odds_id', 'Saas.Lottery/updateOdds');
    Route::delete('admin/lottery-odds/:id/:odds_id', 'Saas.Lottery/deleteOdds');
    // Explicit resource routes avoid the dynamic fallback swallowing nested
    // lottery endpoints such as /admin/lotteries/:id/rules.
    foreach (['admins', 'roles', 'menus', 'settings', 'domains', 'sites'] as $resource) {
        Route::get('admin/'.$resource, 'Saas.Resource/index')->append(['resource' => $resource]);
        Route::post('admin/'.$resource, 'Saas.Resource/create')->append(['resource' => $resource]);
        Route::put('admin/'.$resource.'/:id', 'Saas.Resource/update')->append(['resource' => $resource]);
        Route::delete('admin/'.$resource.'/:id', 'Saas.Resource/delete')->append(['resource' => $resource]);
    }
})->middleware([\app\middleware\ApiContext::class]);
