import { request, type ApiEnvelope } from "../utils/request";

export type Announcement = { title: string; content: string };
export type Agreement = { title: string; content: string };
export type Branding = { platform_name: string; site_id: number | null; site_name: string };
export type RuleSettings = { title: string; content: string; basic?: string; special?: string; amount?: string; text?: string };
export type UserProfile = {
  balance: string;
  total_balance: string;
  credit_balance: string;
  used_balance: string;
  available_balance: string;
  odds?: Array<{ id: number; lottery_name: string; lottery_code: string; category?: string; name: string; min_bet: string; odds_limit: string; single_bet_limit: string; single_item_limit: string; offline_rebate: string; odds: string; direct_category?: number }>;
};

export const getAnnouncement = () => request.get<ApiEnvelope<Announcement>>("/user/announcement");
export const getBranding = () => request.get<ApiEnvelope<Branding>>("/branding", { headers: { "X-Skip-Global-Loading": "1" } });
export const getAgreement = () => request.get<ApiEnvelope<Agreement>>("/user/agreement");
export const getProfile = (params?: Record<string, unknown>) => request.get<ApiEnvelope<UserProfile>>("/user/profile", { params });
export const heartbeat = () => request.post<ApiEnvelope<{ online: boolean; server_time: string }>>("/user/auth/heartbeat");
export const logoutSession = () => request.post<ApiEnvelope<null>>("/user/auth/logout");
export const getRules = (params?: Record<string, unknown>) => request.get<ApiEnvelope<RuleSettings>>("/user/rules", { params });
export type BetRecord = { id: number; issue_no: string; source_text?: string; formatted_text?: string; submission_fingerprint?: string | null; submission_id?: number | null; bet_count: number; amount: string; win_amount: string; status: string; sealed: number; placed_at: string; refunded_at?: string | null; lottery?: string; open_time?: string | null; can_refund?: boolean };
export type StopDrop = { id: number; lottery: string; issue_no: string; number_text: string; play_type: string; stop_type: string; original_amount: string; actual_amount: string; stop_amount: string; original_odds?: string | null; actual_odds?: string | null; drop_odds?: string | null; source_text?: string; placed_at: string };
export type BetDetail = {
  id: number;
  row_key?: string;
  bet_record_id?: number;
  submission_id?: number | null;
  order_no?: string;
  issue_no: string;
  number_text: string;
  category?: string;
  play_type?: string;
  play_label?: string;
  lottery?: string;
  amount: string;
  odds?: string;
  win_amount: string;
  rebate: string;
  offline_rebate?: string;
  profit?: string;
  status: string;
  placed_at: string;
  source_text?: string;
  original_source_text?: string;
  parsed_source_text?: string;
};
export type Bill = { bill_date: string; bet_count: number; amount: string; rebate: string; offline_rebate: string; win_amount: string; profit: string };
export type Draw = { lottery: string; issue_no: string; draw_date: string; draw_time?: string | null; numbers: string; sum_value?: number | null; size?: string | null; parity?: string | null; span_value?: number | null; pending?: number };
export type SiteTimingRule = { start_time: string; end_time: string; allow_bet: number; mask_enabled: number; show_next_issue: number; header_show_next_issue?: number; display_text: string };
export type Lottery = { id: number; name: string; code: string; sort: number; latest_code: string; latest_numbers: string; next_code: string; next_open_time: string | null; header_next_code?: string; header_next_open_time?: string | null; cutoff_enabled?: number; cutoff_time?: string | null; mask_enabled?: number; refund_enabled?: number; timing_rules?: SiteTimingRule[]; timing_text?: string; timing_can_bet?: boolean; timing_mask?: boolean; show_next_issue?: boolean; header_show_next_issue?: boolean; recent_issues?: Array<{ code: string; draw_day: string | null }>; can_bet?: boolean };
export const getLotteries = () => request.get<ApiEnvelope<{ list: Lottery[] }>>("/user/lotteries");
export type LineOption = { line: number; url: string };
export const getLineOptions = () => request.get<ApiEnvelope<{ list: LineOption[] }>>("/user/line-options", { headers: { "X-Skip-Global-Loading": "1" } });
export const getBetRecords = (params?: Record<string, unknown>) => request.get<ApiEnvelope<{ list: BetRecord[]; total: number; amount_total: string }>>("/user/bet-records", { params });
export const refundBetRecord = (id: number) => request.post<ApiEnvelope<{ record_id: number; amount: string }>>(`/user/bet-records/${id}/refund`);
export const getStopDrops = (params?: Record<string, unknown>) => request.get<ApiEnvelope<{ list: StopDrop[]; total: number }>>("/user/stop-drops", { params });
export const getBetDetails = (params?: Record<string, unknown>) => request.get<ApiEnvelope<{
  list: BetDetail[];
  total: number;
  page?: number;
  page_size?: number;
  total_amount?: string;
  win_amount?: string;
  rebate?: string;
  offline_rebate?: string;
  profit?: string;
  page_total?: {
    amount: string;
    win_amount: string;
    rebate: string;
    offline_rebate: string;
    profit: string;
  };
}>>("/user/bet-details", { params });
export const getBills = (params?: Record<string, unknown>) => request.get<ApiEnvelope<{ list: Bill[]; total: Record<string, string | number> }>>("/user/bills", { params });
export const getDraws = (params?: Record<string, unknown>) => request.get<ApiEnvelope<{ list: Draw[] }>>("/user/draws", { params, headers: { "X-Skip-Global-Loading": "1" } });
export const waitDraws = (params?: Record<string, unknown>) => request.get<ApiEnvelope<{ changed: boolean; signature?: string }>>("/user/draws/wait", { params, headers: { "X-Skip-Global-Loading": "1" } });
export const changePassword = (payload: { old_password: string; password: string; confirm_password: string }) => request.post<ApiEnvelope<null>>("/user/auth/password", payload);
export type QuickEntryLine = { id: number; raw_text: string; parse_text?: string; status: "success" | "failed" | "new"; reason?: string | null; number_text: string; display_number_text?: string; category?: string | null; play_type?: string; settlement_text?: string; amount: string; count: number; stake_count?: number; code_count?: number; batch_id?: string; batch_index?: number; batch_size?: number; batch_end?: boolean; batch_valid?: boolean; batch_count?: number; batch_stake_count?: number; batch_amount?: string; batch_number_text?: string; batch_occurrence_text?: string; batch_merged_text?: string; batch_has_duplicates?: boolean; batch_duplicate_numbers?: string[]; batch_declared_stake_count?: number; batch_count_mismatch?: boolean };
export type QuickPreview = { lines: QuickEntryLine[]; count: number; code_count?: number; amount: string; formatted_text: string };
export type QuickTag = { id: number; name: string };
export type QuickSettings = { preferences: Record<string, unknown>; tags: QuickTag[] };
export const previewQuickEntry = (payload: { text: string; lottery: string }) => request.post<ApiEnvelope<QuickPreview>>("/user/quick-entry/preview", payload);
export const placeQuickEntry = (payload: { text: string; lottery: string; confirmed: boolean }) => request.post<ApiEnvelope<{ record_id: number; count: number; amount: string }>>("/user/quick-entry/place", payload);
export const getQuickSettings = () => request.get<ApiEnvelope<QuickSettings>>("/user/quick-entry/settings");
export const saveQuickSettings = (preferences: Record<string, unknown>) => request.put<ApiEnvelope<{ preferences: Record<string, unknown> }>>("/user/quick-entry/settings", { preferences });
export const createQuickTag = (name: string) => request.post<ApiEnvelope<{ id: number; name: string }>>("/user/quick-entry/tags", { name });
export const deleteQuickTag = (id: number) => request.delete<ApiEnvelope<null>>(`/user/quick-entry/tags/${id}`);
