import { DoubleRightOutlined, EditOutlined, LeftOutlined, PlusOutlined, RightOutlined, SearchOutlined } from '@ant-design/icons';
import { App as AntdApp, Empty, Spin, Switch } from 'antd';
import { useEffect, useState } from 'react';
import { apiErrorMessage } from '../../utils/request';
import { batchDeleteAgentSubaccounts, createAgentSubaccount, getAgentSubaccount, getAgentSubaccountOptions, getAgentSubaccounts, updateAgentSubaccount, type AgentSubaccount, type AgentSubaccountIssue, type AgentSubaccountLottery, type AgentSubaccountOption, type AgentSubaccountPayload } from '../../api/user';
import { InitialCredentials } from '../../components/InitialCredentials';
import { hasAgentPermission } from '../../routePermissions';

type View = 'list' | 'form';
type Search = { username: string; displayName: string; status: string };
const emptySearch: Search = { username: '', displayName: '', status: '' };
const emptyForm: AgentSubaccountPayload = { username: '', display_name: '', password: '', status: 1, permissions: [], lottery_permissions: [], report_limit_enabled: 0, report_from_issue: '', report_to_issue: '' };

export function SubaccountsPage() {
  const { message, modal } = AntdApp.useApp();
  const [view, setView] = useState<View>('list'); const [editingId, setEditingId] = useState<number | null>(null);
  const [rows, setRows] = useState<AgentSubaccount[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10);
  const [search, setSearch] = useState<Search>(emptySearch); const [applied, setApplied] = useState<Search>(emptySearch); const [selected, setSelected] = useState<number[]>([]);
  const [permissionOptions, setPermissionOptions] = useState<AgentSubaccountOption[]>([]); const [lotteries, setLotteries] = useState<AgentSubaccountLottery[]>([]); const [issues, setIssues] = useState<AgentSubaccountIssue[]>([]);
  const [form, setForm] = useState<AgentSubaccountPayload>(emptyForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [reload, setReload] = useState(0);
  const canCreate = hasAgentPermission('subaccount.create'); const canUpdate = hasAgentPermission('subaccount.update'); const canDelete = hasAgentPermission('subaccount.delete');

  useEffect(() => { let active = true; void getAgentSubaccountOptions().then((response) => { if (!active) return; setPermissionOptions(response.data.data?.permissions || []); setLotteries(response.data.data?.lotteries || []); setIssues(response.data.data?.issues || []); }).catch(() => { if (active) message.error('权限配置加载失败'); }); return () => { active = false; }; }, [message]);
  useEffect(() => { if (view !== 'list') return; let active = true; setLoading(true); void getAgentSubaccounts({ username: applied.username, display_name: applied.displayName, status: applied.status, page, page_size: pageSize }).then((response) => { if (!active) return; setRows(response.data.data?.list || []); setTotal(response.data.data?.total || 0); setSelected([]); }).catch((reason) => active && message.error(apiErrorMessage(reason, '子账号加载失败'))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [view, applied, page, pageSize, reload, message]);

  const allChecked = rows.length > 0 && rows.every((row) => selected.includes(row.id));
  const openCreate = () => { setEditingId(null); setForm({ ...emptyForm, lottery_permissions: lotteries.map((item) => item.id), report_from_issue: issues[0]?.issue_no || '', report_to_issue: issues[0]?.issue_no || '' }); setView('form'); };
  const openEdit = async (id: number) => { setLoading(true); try { const response = await getAgentSubaccount(id); const data = response.data.data; setEditingId(id); setForm({ username: data.username, display_name: data.display_name, password: '', status: data.status, permissions: data.permissions || [], lottery_permissions: (data.lottery_permissions || []).map(Number), report_limit_enabled: data.report_limit_enabled || 0, report_from_issue: data.report_from_issue || '', report_to_issue: data.report_to_issue || '' }); setView('form'); } catch (reason) { message.error(apiErrorMessage(reason, '子账号加载失败')); } finally { setLoading(false); } };
  const submit = async () => { if (!form.username.trim()) return message.warning('请输入账号名'); if (!editingId && String(form.password || '') !== '' && String(form.password || '').length < 6) return message.warning('密码不能少于6位'); setSaving(true); try { if (editingId) { await updateAgentSubaccount(editingId, form); message.success('子账号修改成功'); } else { const response=await createAgentSubaccount(form); modal.success({title:'子账号创建成功',content:<InitialCredentials value={response.data.data}/>,okText:'我已保存',centered:true,width:480}); } setView('list'); setEditingId(null); setReload((value) => value + 1); } catch (reason) { message.error(apiErrorMessage(reason, '保存失败')); } finally { setSaving(false); } };
  const removeSelected = () => { if (!selected.length) return message.warning('请选择需要删除的子账号'); modal.confirm({ title: '确认删除选中的子账号？', content: '删除后这些账号将无法继续登录。', okText: '删除', cancelText: '取消', okButtonProps: { danger: true }, onOk: async () => { try { await batchDeleteAgentSubaccounts(selected); message.success('删除成功'); setReload((value) => value + 1); } catch (reason) { message.error(apiErrorMessage(reason, '删除失败')); } } }); };

  return <section className="subaccount-page">
    <div className="subaccount-location"><div className="subaccount-path"><strong>位置</strong><DoubleRightOutlined/><span>子账号</span><DoubleRightOutlined/><span>{view === 'list' ? '子账号列表' : editingId ? '修改子账号' : '新建子账号'}</span></div><nav className="subaccount-tabs"><button type="button" className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}>子账号列表</button>{canCreate && <button type="button" className={view === 'form' ? 'active' : ''} onClick={openCreate}>新建子账号</button>}</nav></div>
    {view === 'list' ? <>
      <form className="subaccount-search" onSubmit={(event) => { event.preventDefault(); setPage(1); setApplied({ ...search }); }}><label><span>用户名：</span><input placeholder="搜索用户名" value={search.username} onChange={(event) => setSearch({ ...search, username: event.target.value })}/></label><label><span>代号：</span><input placeholder="搜索代号" value={search.displayName} onChange={(event) => setSearch({ ...search, displayName: event.target.value })}/></label><label><span>状态：</span><select value={search.status} onChange={(event) => setSearch({ ...search, status: event.target.value })}><option value="">所有状态</option><option value="1">启用</option><option value="0">停用</option></select></label><button type="submit"><SearchOutlined/>搜索</button>{canDelete && <button type="button" className="subaccount-delete" onClick={removeSelected}>删 除</button>}</form>
      <div className="subaccount-card">{loading ? <div className="subaccount-state"><Spin/></div> : rows.length ? <table className="subaccount-table"><thead><tr><th>{canDelete && <input type="checkbox" aria-label="全选" checked={allChecked} onChange={(event) => setSelected(event.target.checked ? rows.map((row) => row.id) : [])}/>} 编号</th><th>账号名</th><th>代号</th><th>启/停用</th><th>最后登录</th><th>最后登录地点</th><th>内容</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id}><td>{canDelete && <input type="checkbox" aria-label={`选择${row.username}`} checked={selected.includes(row.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, row.id] : selected.filter((id) => id !== row.id))}/>}<span>{(page - 1) * pageSize + index + 1}</span></td><td>{row.username}</td><td>{row.display_name}</td><td>{canUpdate ? <Switch size="small" checked={row.status === 1} checkedChildren="启用" unCheckedChildren="停用" onChange={async (checked) => { try { const detail = (await getAgentSubaccount(row.id)).data.data; await updateAgentSubaccount(row.id, { username: detail.username, display_name: detail.display_name, password: '', status: checked ? 1 : 0, permissions: detail.permissions || [], lottery_permissions: detail.lottery_permissions || [], report_limit_enabled: detail.report_limit_enabled || 0, report_from_issue: detail.report_from_issue || '', report_to_issue: detail.report_to_issue || '' }); setReload((value) => value + 1); } catch (reason) { message.error(apiErrorMessage(reason, '状态修改失败')); } }}/> : row.status === 1 ? '启用' : '停用'}</td><td>{row.last_login_at || '---'}</td><td>{row.last_login_location || '---'}</td><td>{canUpdate ? <button type="button" onClick={() => void openEdit(row.id)}><EditOutlined/>修改</button> : <span>—</span>}</td></tr>)}</tbody></table> : <div className="subaccount-state"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无数据"/></div>}</div>
      <Pagination total={total} page={page} pageSize={pageSize} setPage={setPage} setPageSize={(value) => { setPage(1); setPageSize(value); }}/>
    </> : <SubaccountForm form={form} setForm={setForm} options={permissionOptions} lotteries={lotteries} issues={issues} editing={editingId !== null} saving={saving} submit={() => void submit()}/>}
  </section>;
}

function Pagination({ total, page, pageSize, setPage, setPageSize }: { total: number; page: number; pageSize: number; setPage: (value: number) => void; setPageSize: (value: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <div className="subaccount-pagination"><span>总计：<b>{total}</b> 条数据</span><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)}><LeftOutlined/></button><strong>{page}</strong><button type="button" disabled={page >= pages} onClick={() => setPage(page + 1)}><RightOutlined/></button><select value={pageSize} onChange={(event) => setPageSize(Number(event.target.value))}><option value={10}>10 条/页</option><option value={20}>20 条/页</option><option value={50}>50 条/页</option></select></div>; }

function SubaccountForm({ form, setForm, options, lotteries, issues, editing, saving, submit }: { form: AgentSubaccountPayload; setForm: (value: AgentSubaccountPayload) => void; options: AgentSubaccountOption[]; lotteries: AgentSubaccountLottery[]; issues: AgentSubaccountIssue[]; editing: boolean; saving: boolean; submit: () => void }) {
  const allPermissions = options.length > 0 && options.every((item) => form.permissions.includes(item.key)); const issueLabel = (item: AgentSubaccountIssue) => `${Number(item.date.slice(5,7))}-${Number(item.date.slice(8,10))}(${item.issue_no})`;
  return <div className="subaccount-form"><section className="subaccount-account-fields"><label><span>账号名</span><input placeholder="请输入账号名" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })}/></label><label><span>代号</span><input placeholder="请输入代号" value={form.display_name} onChange={(event) => setForm({ ...form, display_name: event.target.value })}/></label><label><span>密码</span><input type="password" placeholder={editing ? '不修改请留空' : '可留空，系统自动生成'} value={form.password || ''} onChange={(event) => setForm({ ...form, password: event.target.value })}/></label><p>新建时密码可以留空；系统生成或填写的初始密码都要求首次登录后修改。</p></section>
    <section className="subaccount-report-limit"><label>报表期限：<span>设置起始和结束期号</span><input type="checkbox" checked={form.report_limit_enabled === 1} onChange={(event) => setForm({ ...form, report_limit_enabled: event.target.checked ? 1 : 0 })}/></label>{form.report_limit_enabled === 1 && <div><select value={form.report_from_issue} onChange={(event) => setForm({ ...form, report_from_issue: event.target.value })}>{issues.map((item) => <option key={`from-${item.issue_no}`} value={item.issue_no}>{issueLabel(item)}</option>)}</select><span>至</span><select value={form.report_to_issue} onChange={(event) => setForm({ ...form, report_to_issue: event.target.value })}>{issues.map((item) => <option key={`to-${item.issue_no}`} value={item.issue_no}>{issueLabel(item)}</option>)}</select></div>}</section>
    <section className="subaccount-lotteries">{lotteries.map((lottery) => <label key={lottery.id}><b>{lottery.name}：</b><span>权限</span><Switch size="small" checked={form.lottery_permissions.includes(lottery.id)} onChange={(checked) => setForm({ ...form, lottery_permissions: checked ? [...form.lottery_permissions, lottery.id] : form.lottery_permissions.filter((id) => id !== lottery.id) })}/></label>)}</section>
    <section className="subaccount-permissions"><header><strong>权限列表</strong><label>全选 <Switch size="small" checked={allPermissions} checkedChildren="是" unCheckedChildren="否" onChange={(checked) => setForm({ ...form, permissions: checked ? options.map((item) => item.key) : [] })}/></label></header><div>{options.map((item) => <label key={item.key}><span>{item.label}</span><Switch size="small" checked={form.permissions.includes(item.key)} checkedChildren="有" unCheckedChildren="无" onChange={(checked) => setForm({ ...form, permissions: checked ? [...form.permissions, item.key] : form.permissions.filter((key) => key !== item.key) })}/></label>)}</div></section>
    <button className="subaccount-save" type="button" disabled={saving} onClick={submit}><PlusOutlined/>{saving ? '提交中' : '提 交'}</button></div>;
}
