import { DoubleRightOutlined } from '@ant-design/icons';
import { Empty, Select, Spin } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { getLedger, getLedgerIssues, type ContributionRow, type LedgerIssue, type LedgerRow } from '../../api/user';

type LedgerView='contribution'|'daily'|'monthly'|'daily_path'|'monthly_path';
const views:Array<{key:LedgerView;label:string}>=[{key:'contribution',label:'贡献度'},{key:'daily',label:'日分类账'},{key:'monthly',label:'月分类账'},{key:'daily_path',label:'日路径账'},{key:'monthly_path',label:'月路径账'}];
const ledgerPermission:Record<LedgerView,string>={contribution:'contribution',daily:'daily_ledger',monthly:'monthly_ledger',daily_path:'daily_path',monthly_path:'monthly_path'};
const storedPermissions=()=>{try{const value=JSON.parse(localStorage.getItem('agent_permissions')||'["*"]');return Array.isArray(value)?value.map(String):['*']}catch{return['*']}};

export function LedgerPage({lottery}:{lottery:string}) {
  const allowedViews=views.filter(item=>{const permissions=storedPermissions();return permissions.includes('*')||permissions.includes(ledgerPermission[item.key])});
  const [view,setView]=useState<LedgerView>(()=>allowedViews[0]?.key||'contribution');const [issues,setIssues]=useState<LedgerIssue[]>([]);const [fromIssue,setFromIssue]=useState('');const [toIssue,setToIssue]=useState('');const [rows,setRows]=useState<Array<LedgerRow|ContributionRow>>([]);const [loading,setLoading]=useState(true);
  const isDaily=view==='daily'||view==='daily_path';const activeLabel=views.find(item=>item.key===view)?.label||'贡献度';
  useEffect(()=>{if(!lottery){setIssues([]);return;}let active=true;void getLedgerIssues({lottery}).then(response=>{if(!active)return;const list=response.data.data?.list||[];setIssues(list);if(list.length){setToIssue(list[0].issue_no);setFromIssue(view==='contribution'||isDaily?list[0].issue_no:list[list.length-1].issue_no);}}).catch(()=>active&&setIssues([]));return()=>{active=false}},[lottery]);
  const params=useMemo(()=>({lottery,view,from_issue:isDaily?toIssue:fromIssue,to_issue:toIssue}),[lottery,view,fromIssue,toIssue,isDaily]);
  useEffect(()=>{if(!lottery||!toIssue){setRows([]);setLoading(false);return;}let active=true;setLoading(true);void getLedger(params).then(response=>{if(active)setRows(response.data.data?.list||[])}).catch(()=>active&&setRows([])).finally(()=>active&&setLoading(false));return()=>{active=false}},[lottery,toIssue,params]);
  const setRange=(type:'current'|'all'|'week'|'lastWeek')=>{if(!issues.length)return;if(type==='current'){setFromIssue(issues[0].issue_no);setToIssue(issues[0].issue_no);return;}if(type==='all'){setFromIssue(issues[issues.length-1].issue_no);setToIssue(issues[0].issue_no);return;}const now=new Date();const day=now.getDay()||7;const monday=new Date(now);monday.setDate(now.getDate()-day+1);monday.setHours(0,0,0,0);let start=monday;let end=now;if(type==='lastWeek'){start=new Date(monday);start.setDate(start.getDate()-7);end=new Date(monday);end.setDate(end.getDate()-1);}const within=issues.filter(item=>{const date=new Date(`${item.date}T12:00:00`);return date>=start&&date<=end});if(within.length){setFromIssue(within[within.length-1].issue_no);setToIssue(within[0].issue_no);}};
  const month=issues.find(item=>item.issue_no===toIssue)?.date.slice(0,7)||new Date().toISOString().slice(0,7);
  return <section className="ledger-reference-page">
    <div className="ledger-reference-location"><div className="ledger-reference-path"><strong>位置</strong><DoubleRightOutlined/><span>分类账</span><DoubleRightOutlined/><span>{activeLabel}</span></div><nav className="ledger-reference-tabs">{allowedViews.map(item=><button type="button" key={item.key} className={view===item.key?'active':''} onClick={()=>{setView(item.key);if(issues.length){setToIssue(issues[0].issue_no);setFromIssue(item.key==='contribution'||item.key==='daily'||item.key==='daily_path'?issues[0].issue_no:issues[issues.length-1].issue_no)}}}>{item.label}</button>)}</nav></div>
    <div className="ledger-reference-band"><strong>{activeLabel}</strong>{isDaily?<b>第 {toIssue||'---'} 期</b>:<><b>【{month.replace('-','年')}月】</b>{view==='contribution'&&<button type="button" className="current" onClick={()=>setRange('current')}>【本期】</button>}<button type="button" onClick={()=>setRange('all')}>【全部】</button><button type="button" onClick={()=>setRange('week')}>【本周】</button><button type="button" onClick={()=>setRange('lastWeek')}>【上周】</button></>}{!isDaily&&<div className="ledger-issue-range"><IssueSelect label="开始期号" value={fromIssue} issues={issues} onChange={setFromIssue}/><span>至</span><IssueSelect label="结束期号" value={toIssue} issues={issues} onChange={setToIssue}/></div>}</div>
    <div className="ledger-reference-card">{loading?<div className="ledger-reference-state"><Spin/></div>:rows.length?<LedgerTable view={view} rows={rows}/>:<div className="ledger-reference-state"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无数据"/></div>}</div>
  </section>;
}

function IssueSelect({label,value,issues,onChange}:{label:string;value:string;issues:LedgerIssue[];onChange:(value:string)=>void}) {return <Select className="ledger-issue-select" size="small" aria-label={label} value={value} onChange={onChange} options={issues.map(item=>({value:item.issue_no,label:`${Number(item.date.slice(5,7))}-${Number(item.date.slice(8,10))}(${item.issue_no})` }))} />}
function LedgerTable({view,rows}:{view:LedgerView;rows:Array<LedgerRow|ContributionRow>}) {
  if(view==='contribution')return <table className="ledger-reference-table contribution-table"><thead><tr><th>会员</th><th>占成金额</th><th>占成总金额</th><th>占成总盈亏</th><th>明水</th><th>百分比占成盈亏</th><th>实际占成盈亏</th><th>占成百分比</th><th>贡献度</th></tr></thead><tbody>{(rows as ContributionRow[]).map(row=><tr key={row.member}><td>{row.member}</td><td>{row.share_amount}</td><td>{row.share_total_amount}</td><td>{row.share_total_profit}</td><td>{row.water}</td><td>{row.percentage_share_profit}</td><td>{row.actual_share_profit}</td><td>{row.share_percentage}</td><td>{row.contribution}</td></tr>)}</tbody></table>;
  const monthly=view==='monthly'||view==='monthly_path';return <table className="ledger-reference-table"><thead><tr><th>{monthly?'期号':'代理'}</th><th>类别</th><th>笔数</th><th>总投</th><th>回水</th><th>明水</th><th>中奖</th><th>盈亏</th></tr></thead><tbody>{(rows as LedgerRow[]).map((row,index)=><tr key={`${row.label}-${row.category}-${index}`}><td>{row.label}</td><td>{row.category}</td><td>{row.bet_count}</td><td>{row.amount}</td><td>{row.rebate}</td><td>{row.water}</td><td>{row.win_amount}</td><td>{row.profit}</td></tr>)}</tbody></table>;
}
