<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { listResource, getSiteOrganizations, listAgentImportProfiles, saveAgentImportProfile, probeAgentImport, listAgentImportBatches, createAgentImportBatch, rollbackAgentImportBatch, getAgentImportCredentials, type AgentImportProfile, type AgentImportBatch } from '../api/admin'
const sites=ref<any[]>([]), siteId=ref(0), orgs=ref<any[]>([]), profiles=ref<AgentImportProfile[]>([]), batches=ref<AgentImportBatch[]>([]), probing=ref<number|null>(null), saving=ref(false), running=ref(false)
const form=ref<AgentImportProfile>({site_id:0,name:'参考站数据源',base_url:'',username:'',password:'',enabled:1})
let batchPollTimer:ReturnType<typeof setInterval>|null=null
const batch=ref({profile_id:0,target_organization_id:0,from_date:new Date().toISOString().slice(0,10),to_date:new Date().toISOString().slice(0,10)})
async function loadSites(){const r=await listResource('sites');sites.value=r.data.list||[];if(!siteId.value&&sites.value[0])siteId.value=Number(sites.value[0].id)}
async function load(){if(!siteId.value)return;const [p,o,b]=await Promise.all([listAgentImportProfiles(siteId.value),getSiteOrganizations(siteId.value),listAgentImportBatches(siteId.value)]);profiles.value=p.data.list||[];orgs.value=o.data.nodes||[];batches.value=b.data.list||[];if(!form.value.site_id)form.value.site_id=siteId.value;if(!batch.value.profile_id&&profiles.value[0])batch.value.profile_id=Number(profiles.value[0].id);if(!batch.value.target_organization_id&&orgs.value[0])batch.value.target_organization_id=Number(orgs.value[0].id)}
watch(siteId,()=>{form.value.site_id=siteId.value;void load()}); onMounted(()=>{void loadSites();batchPollTimer=setInterval(()=>{if(batches.value.some((row:any)=>row.status==='queued'||row.status==='running'))void load()},5000)}); onBeforeUnmount(()=>{if(batchPollTimer)clearInterval(batchPollTimer)})
async function save(){saving.value=true;try{await saveAgentImportProfile({...form.value,site_id:siteId.value});ElMessage.success('配置已保存');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{saving.value=false}}
async function probe(id:number){probing.value=id;try{const r=await probeAgentImport(id);const calls=Array.isArray(r?.data?.calls)?r.data.calls:[];if(calls.length===0)throw new Error('探测接口未返回有效结果，请检查参考站账号、密码和地址');const ok=calls.filter(x=>!x.error).length;ElMessage.success(`探测完成：${ok}/${calls.length} 个接口返回`);console.info('总代理接口探测',calls);await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'探测失败')}finally{probing.value=null}}
async function start(){running.value=true;try{const r=await createAgentImportBatch({...batch.value,site_id:siteId.value});if((r.data as any)?.queued){ElMessage.success('做账任务已进入后台，可继续操作；完成后刷新批次列表查看结果');await load();return}const counts=r.data.created_counts||{};const credentials=r.data.credentials||[];ElMessage.success(`做账完成：代理${counts.created_nodes||0}个、会员${counts.created_members||0}个、账号${counts.created_accounts||0}个`);if(credentials.length){const text=credentials.map((item:any)=>`${item.type==='agent'?'代理':'会员'}：${item.username} / 初始密码：${item.initial_password}`).join('<br>');await ElMessageBox.alert(text,'新建账号初始密码',{dangerouslyUseHTMLString:true,confirmButtonText:'关闭'});}await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'创建失败')}finally{running.value=false}}
async function rollback(id:number){await ElMessageBox.confirm('仅回滚该批次产生的映射和新增数据，继续？','确认回滚');try{await rollbackAgentImportBatch(id);ElMessage.success('批次已回滚');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'回滚失败')}}
async function showCredentials(id:number){try{const r=await getAgentImportCredentials(id);const credentials=r.data.credentials||[];if(!credentials.length){ElMessage.info('该批次没有保存的明文密码');return}const text=credentials.map((item:any)=>`${item.type==='agent'?'代理':'会员'}：${item.username} / 初始密码：${item.initial_password}`).join('<br>');await ElMessageBox.alert(text,'账号密码',{dangerouslyUseHTMLString:true,confirmButtonText:'关闭'});}catch(e){ElMessage.error(e instanceof Error?e.message:'读取失败')}}
</script>
<template><div class="import-page"><div class="heading"><div><h2>账号树做账</h2><p>先探测真实接口，再按批次导入；可从任意组织层级开始，自动保留下级父子关系。</p></div><el-select v-model="siteId" placeholder="选择站点" style="width:220px"><el-option v-for="s in sites" :key="s.id" :value="s.id" :label="s.name"/></el-select></div>
<el-card shadow="never"><template #header>参考站账号配置</template><el-form label-position="top"><el-row :gutter="14"><el-col :span="6"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item></el-col><el-col :span="8"><el-form-item label="参考站 Base URL"><el-input v-model="form.base_url" placeholder="https://HOST"/></el-form-item></el-col><el-col :span="5"><el-form-item label="登录账号"><el-input v-model="form.username"/></el-form-item></el-col><el-col :span="5"><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password placeholder="已保存可留空"/></el-form-item></el-col></el-row><el-button type="primary" :loading="saving" @click="save">保存配置</el-button></el-form><el-table :data="profiles" style="margin-top:16px"><el-table-column prop="name" label="名称"/><el-table-column prop="base_url" label="地址"/><el-table-column prop="username" label="账号"/><el-table-column prop="last_probe_status" label="探测状态"/><el-table-column prop="last_probe_at" label="最近探测"/><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" :loading="probing===row.id" @click="probe(row.id)">探测接口</el-button></template></el-table-column></el-table></el-card>
<el-card shadow="never" style="margin-top:16px"><template #header>创建做账批次</template><p style="margin:0 0 12px;color:#8490a5;font-size:13px">选择本地任意起始组织；导入时会按参考站返回的父子关系继续创建下级组织和会员。</p><el-form inline><el-form-item label="数据源"><el-select v-model="batch.profile_id" style="width:220px"><el-option v-for="p in profiles" :key="p.id" :value="p.id" :label="`${p.name}（${p.username}）`"/></el-select></el-form-item><el-form-item label="写入起始组织"><el-select v-model="batch.target_organization_id" style="width:220px"><el-option v-for="o in orgs" :key="o.id" :value="o.id" :label="`${o.name}（${o.level}）`"/></el-select></el-form-item><el-form-item label="开始"><el-date-picker v-model="batch.from_date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="结束"><el-date-picker v-model="batch.to_date" value-format="YYYY-MM-DD"/></el-form-item><el-button type="primary" :loading="running" @click="start">开始做账</el-button></el-form></el-card>
<el-card shadow="never" style="margin-top:16px"><template #header>批次与回滚</template><el-table :data="batches"><el-table-column prop="id" label="批次" width="80"/><el-table-column prop="from_date" label="开始"/><el-table-column prop="to_date" label="结束"/><el-table-column prop="status" label="状态"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.created_counts" link type="primary" @click="showCredentials(row.id)">查看账号密码</el-button><el-button v-if="row.status==='completed'" link type="danger" @click="rollback(row.id)">回滚</el-button></template></el-table-column></el-table></el-card></div></template>
<style scoped>.import-page{padding:22px;background:#fff;min-height:100%}.heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.heading h2{margin:0 0 6px}.heading p{margin:0;color:#8490a5;font-size:13px}</style>
