<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createLottery, deleteLottery, listLotteries, updateLottery, type Lottery } from '../api/admin'
import { useRouter } from 'vue-router'

const router=useRouter()
const loading = ref(false); const rows = ref<Lottery[]>([]); const drawer = ref(false); const editing = ref<Lottery | null>(null)
const form = ref({ name: '', code: '', unit_stake: 2, source_type: 'official' as 'official'|'system', system_interval_seconds: 60, system_issue_mode: 'auto' as 'auto'|'manual', system_initial_issue: '', odds_source_lottery_id: null as number|null, status: 1, sort: 0 })
async function load() { loading.value = true; try { const lotteries = await listLotteries({ page: 1, page_size: 100 }); rows.value = lotteries.data.list } catch (e) { ElMessage.error(e instanceof Error ? e.message : '彩票列表加载失败') } finally { loading.value = false } }
function emptyForm() { return { name: '', code: '', unit_stake: 2, source_type: 'official' as 'official'|'system', system_interval_seconds: 60, system_issue_mode: 'auto' as 'auto'|'manual', system_initial_issue: '', odds_source_lottery_id: null as number|null, status: 1, sort: 0 } }
function openCreate() { editing.value = null; form.value = emptyForm(); drawer.value = true }
function openEdit(row: Lottery) { editing.value = row; form.value = { name: row.name, code: row.code, unit_stake: Number(row.unit_stake || 2), source_type: row.source_type || 'official', system_interval_seconds: Number(row.system_interval_seconds || 60), system_issue_mode: row.system_issue_mode || 'auto', system_initial_issue: row.system_initial_issue || '', odds_source_lottery_id: row.odds_source_lottery_id ? Number(row.odds_source_lottery_id) : null, status: row.status, sort: row.sort }; drawer.value = true }
async function save() { try { if (!form.value.name.trim() || !form.value.code.trim()) return ElMessage.warning('请填写彩票名称和编码'); if (!(form.value.unit_stake > 0)) return ElMessage.warning('单注彩票金额必须大于0'); if (form.value.source_type === 'system' && (form.value.system_issue_mode === 'manual' && !form.value.system_initial_issue.trim() || form.value.system_interval_seconds < 5)) return ElMessage.warning('系统彩请设置有效的起始期号方式和至少5秒的开奖间隔'); if (editing.value?.id) await updateLottery(editing.value.id, form.value); else await createLottery(form.value); drawer.value = false; ElMessage.success('彩票配置已保存'); await load() } catch (e) { ElMessage.error(e instanceof Error ? e.message : '保存失败') } }
async function remove(row: Lottery) { try { await ElMessageBox.confirm(`确定删除“${row.name}”吗？删除后所有站点都不可见。`, '删除彩票', { type: 'warning' }); await deleteLottery(row.id); ElMessage.success('彩票已删除'); await load() } catch (e) { if (e !== 'cancel') ElMessage.error(e instanceof Error ? e.message : '删除失败') } }
onMounted(load)
</script>

<template>
  <div class="lotteries-page">
    <div class="page-heading"><div><h2>彩票列表</h2><p>维护全平台彩票资料；站点可见彩票请在代理中心编辑对应站点。</p></div><el-button type="primary" @click="openCreate">新增彩票</el-button></div>
    <el-card shadow="never" class="lottery-card"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="name" label="彩票名称" min-width="180"/><el-table-column prop="code" label="编码" min-width="140"/><el-table-column label="来源" width="100"><template #default="{ row }"><el-tag :type="row.source_type === 'system' ? 'warning' : 'success'">{{ row.source_type === 'system' ? '系统彩' : '官方彩' }}</el-tag></template></el-table-column><el-table-column label="单注金额" width="120"><template #default="{ row }">{{ Number(row.unit_stake || 2).toFixed(2) }} 元</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status ? 'success' : 'info'">{{ row.status ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="410" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="router.push({name:'lottery-history',params:{id:row.id},query:{name:row.name}})">开奖历史</el-button><el-button link type="primary" @click="router.push({name:'lottery-odds',params:{id:row.id},query:{name:row.name}})">赔率详情</el-button><el-button link type="primary" @click="router.push({name:'lottery-rules',params:{id:row.id},query:{name:row.name}})">规则配置</el-button><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></el-card>
    <el-drawer v-model="drawer" :title="editing ? '编辑彩票' : '新增彩票'" size="500px"><el-form label-position="top"><el-form-item label="彩票名称" required><el-input v-model="form.name" placeholder="例如：福彩3D"/></el-form-item><el-form-item label="彩票编码" required><el-input v-model="form.code" :disabled="!!editing" placeholder="例如：fc3d"/></el-form-item><el-form-item label="彩种来源"><el-radio-group v-model="form.source_type"><el-radio value="official">官方彩（定时获取官方开奖）</el-radio><el-radio value="system">系统彩（本地随机开奖）</el-radio></el-radio-group></el-form-item><template v-if="form.source_type === 'system'"><el-form-item label="开奖间隔（秒）" required><el-input-number v-model="form.system_interval_seconds" :min="5" :max="86400" :step="5" controls-position="right" style="width:100%"/></el-form-item><el-form-item label="起始期号方式"><el-radio-group v-model="form.system_issue_mode"><el-radio value="auto">系统自动生成</el-radio><el-radio value="manual">手动填写</el-radio></el-radio-group><div class="field-tip">自动模式按北京时间生成“年月日＋当天时间序号”：例如每分钟一期，01:37 对应 2608260097。</div></el-form-item><el-form-item v-if="form.system_issue_mode === 'manual'" label="起始期号" required><el-input v-model="form.system_initial_issue" placeholder="例如：2608260000"/></el-form-item><div class="field-tip">系统会预先随机生成下一期号码，到开奖时间才正式开放并结算。</div></template><el-form-item label="赔率来源"><el-select v-model="form.odds_source_lottery_id" clearable placeholder="可选择其他彩种赔率" style="width:100%"><el-option v-for="item in rows.filter(item => item.id !== editing?.id)" :key="item.id" :label="`${item.name}（${item.source_type === 'system' ? '系统彩' : '官方彩'}）`" :value="item.id"/></el-select><div class="field-tip">保存时会复制所选彩种的类别和玩法赔率，之后可独立调整。</div></el-form-item><el-form-item label="单注彩票金额" required><el-input-number v-model="form.unit_stake" :min="0.01" :max="1000000" :precision="2" :step="1" controls-position="right" style="width:100%"/><div class="field-tip">用于换算“倍数”：单注2元时，3倍表示每个号码6元。</div></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sort" :min="0" :max="9999"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" active-text="启用" inactive-text="停用"/></el-form-item></el-form><template #footer><el-button @click="drawer = false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-drawer>
  </div>
</template>

<style scoped>
.lotteries-page { min-height: 100%; padding: 22px; background:#fff; }.page-heading { display:flex; align-items:center; justify-content:space-between; margin-bottom:18px; }.page-heading h2 { margin:0 0 7px; color:#25314a; font-size:20px; }.page-heading p { margin:0; color:#8490a5; font-size:13px; }.lottery-card { border:1px solid #e8edf4; }.field-tip{margin-top:7px;color:#8490a5;font-size:12px;line-height:1.5}
</style>
