<?php
use think\facade\Route;
Route::group('api/v1', static function () {
    Route::get('health', 'Health/index');
    Route::options('health', 'Health/index');
    Route::get('branding', 'Branding/index');
    Route::get('security-policy', 'SecuritySettings/policy');
    Route::post('admin/auth/login', 'Auth/adminLogin');
    Route::post('admin/auth/logout', 'Auth/logout');
    Route::post('admin/auth/heartbeat', 'Auth/heartbeat');
    Route::get('admin/auth/menus', 'Auth/menus');
    Route::get('admin/system-settings/security', 'SecuritySettings/adminPolicy');
    Route::put('admin/system-settings/security', 'SecuritySettings/saveAdminPolicy');
    Route::get('admin/system-settings/branding', 'Branding/adminSettings');
    Route::put('admin/system-settings/branding', 'Branding/saveAdminSettings');
    Route::post('user/auth/login', 'Auth/userLogin');
    Route::post('user/auth/logout', 'Auth/logout');
    Route::post('user/auth/heartbeat', 'Auth/heartbeat');
    Route::get('user/auth/captcha', 'Auth/captcha');
    Route::post('user/auth/captcha/verify', 'Auth/verifyCaptcha');
    Route::post('agent/auth/login', 'Auth/agentLogin');
    Route::post('agent/auth/logout', 'Auth/logout');
    Route::post('agent/auth/heartbeat', 'Auth/heartbeat');
    Route::post('agent/auth/password', 'Auth/changeAgentPassword');
    Route::get('agent/auth/captcha', 'Auth/captcha');
    Route::post('agent/auth/captcha/verify', 'Auth/verifyCaptcha');
    Route::get('agent/profile', 'Organization/profile');
    Route::get('agent/organizations', 'Organization/agentIndex')->completeMatch();
    Route::post('agent/organizations', 'Organization/agentCreateNode')->completeMatch();
    Route::put('agent/organizations/:id', 'Organization/agentUpdateNode');
    Route::delete('agent/organizations/:id', 'Organization/agentDeleteNode');
    Route::post('agent/organizations/:organizationId/accounts', 'Organization/agentCreateAccount');
    Route::put('agent/organization-accounts/:id', 'Organization/agentUpdateAccount');
    Route::delete('agent/organization-accounts/:id', 'Organization/agentDeleteAccount');
    Route::get('agent/profit-shares', 'Organization/agentProfitShare');
    Route::put('agent/profit-shares/:childId', 'Organization/agentSaveProfitShare');
    Route::get('agent/agreement', 'SiteSettings/agentAgreement');
    Route::get('agent/announcement', 'SiteSettings/agentAnnouncement');
    Route::get('agent/rules', 'SiteSettings/agentRules');
    Route::get('agent/lotteries', 'Lottery/agent');
    Route::get('agent/line-options', 'AgentLine/options');
    Route::get('agent/members/:id', 'AgentMember/detail');
    Route::put('agent/members/:id', 'AgentMember/update');
    Route::get('agent/members', 'AgentMember/index');
    Route::post('agent/members', 'AgentMember/create');
    Route::get('agent/report-categories', 'AgentBusiness/categories');
    Route::get('agent/order-details', 'AgentBusiness/orderDetails');
    Route::get('agent/winning-details', 'AgentBusiness/winningDetails');
    Route::get('agent/bet-records', 'AgentBusiness/betRecords');
    Route::get('agent/refunds', 'AgentBusiness/refunds');
    Route::get('agent/ledger/issues', 'AgentLedger/issues');
    Route::get('agent/ledger', 'AgentLedger/index')->completeMatch();
    Route::get('agent/interceptions/issues', 'AgentInterception/issues');
    Route::get('agent/interceptions/categories', 'AgentInterception/categories');
    Route::get('agent/interceptions/plate', 'AgentInterception/plate');
    Route::get('agent/interceptions', 'AgentInterception/index')->completeMatch();
    Route::get('agent/results', 'AgentResults/index');
    Route::get('agent/reports/monthly', 'AgentReport/monthly');
    Route::get('agent/reports/issues', 'AgentReport/issues');
    Route::get('agent/reports', 'AgentReport/index')->completeMatch();
    Route::get('agent/audit-logs', 'AuditLog/index');
    Route::get('agent/settings', 'AgentSettings/index');
    Route::put('agent/settings', 'AgentSettings/save');
    Route::get('agent/subaccounts/options', 'AgentSubaccount/options');
    Route::post('agent/subaccounts/batch-delete', 'AgentSubaccount/batchDelete');
    Route::get('agent/subaccounts/:id', 'AgentSubaccount/detail');
    Route::put('agent/subaccounts/:id', 'AgentSubaccount/update');
    Route::delete('agent/subaccounts/:id', 'AgentSubaccount/delete');
    Route::get('agent/subaccounts', 'AgentSubaccount/index')->completeMatch();
    Route::post('agent/subaccounts', 'AgentSubaccount/create')->completeMatch();
    Route::get('user/agreement', 'SiteSettings/userAgreement');
    Route::get('user/profile', 'Auth/userProfile');
    Route::post('user/auth/password', 'Auth/changeUserPassword');
    Route::get('user/announcement', 'SiteSettings/userAnnouncement');
    Route::get('user/rules', 'SiteSettings/userRules');
    Route::get('user/lotteries', 'Lottery/user');
    Route::get('user/line-options', 'UserBusiness/lineOptions');
    Route::get('user/bet-records', 'UserBusiness/betRecords');
    Route::post('user/bet-records/:id/refund', 'UserBusiness/refundBetRecord');
    Route::get('user/stop-drops', 'UserBusiness/stopDrops');
    Route::get('user/bet-details', 'UserBusiness/betDetails');
    Route::get('user/bills', 'UserBusiness/bills');
    Route::get('user/draws', 'UserBusiness/draws');
    Route::get('user/draws/wait', 'UserBusiness/waitDraws');
    Route::post('user/quick-entry/preview', 'UserBusiness/quickPreview');
    Route::post('user/quick-entry/place', 'UserBusiness/quickPlace');
    Route::get('user/quick-entry/settings', 'UserBusiness/quickSettings');
    Route::put('user/quick-entry/settings', 'UserBusiness/saveQuickSettings');
    Route::post('user/quick-entry/tags', 'UserBusiness/createQuickTag');
    Route::delete('user/quick-entry/tags/:id', 'UserBusiness/deleteQuickTag');
    // Hyphenated resource names need explicit routes because the dynamic
    // segment parser treats the hyphen as a separator.
    Route::get('admin/sub-agents', 'Resource/index')->append(['resource' => 'sub-agents']);
    Route::post('admin/sub-agents', 'Resource/create')->append(['resource' => 'sub-agents']);
    Route::put('admin/sub-agents/:id', 'Resource/update')->append(['resource' => 'sub-agents']);
    Route::delete('admin/sub-agents/:id', 'Resource/delete')->append(['resource' => 'sub-agents']);
    Route::get('admin/audit-logs', 'Resource/index')->append(['resource' => 'audit-logs']);
    Route::delete('admin/audit-logs', 'Resource/clearAuditLogs')->completeMatch();
    Route::get('admin/audit-logs/:id', 'Resource/auditDetail');
    Route::get('admin/score-ledger/overview', 'ScoreLedger/overview');
    Route::get('admin/dashboard/score', 'ScoreLedger/dashboard');
    Route::put('admin/score-ledger/total', 'ScoreLedger/updateTotal');
    Route::get('admin/score-ledger/:id', 'ScoreLedger/detail');
    Route::get('admin/score-ledger', 'ScoreLedger/index')->completeMatch();
    Route::get('admin/agent-center/:id/enter', 'Auth/adminEnter');
    Route::get('admin/sites/:siteId/organizations', 'Organization/adminIndex');
    Route::post('admin/sites/:siteId/organizations', 'Organization/adminCreateNode');
    Route::put('admin/organizations/:id', 'Organization/adminUpdateNode');
    Route::delete('admin/organizations/:id', 'Organization/adminDeleteNode');
    Route::post('admin/organizations/:organizationId/accounts', 'Organization/adminCreateAccount');
    Route::put('admin/organization-accounts/:id', 'Organization/adminUpdateAccount');
    Route::delete('admin/organization-accounts/:id', 'Organization/adminDeleteAccount');
    Route::get('admin/sites/:siteId/profit-shares', 'Organization/adminProfitShare');
    Route::put('admin/sites/:siteId/profit-shares/:childId', 'Organization/adminSaveProfitShare');
    Route::get('admin/agent-center', 'Resource/index')->append(['resource' => 'agent-center']);
    Route::post('admin/agent-center', 'Resource/create')->append(['resource' => 'agent-center']);
    Route::put('admin/agent-center/:id', 'Resource/update')->append(['resource' => 'agent-center']);
    Route::delete('admin/agent-center/:id', 'Resource/delete')->append(['resource' => 'agent-center']);
    Route::get('admin/site-admins', 'Resource/index')->append(['resource' => 'site-admins']);
    Route::post('admin/site-admins', 'Resource/create')->append(['resource' => 'site-admins']);
    Route::put('admin/site-admins/:id', 'Resource/update')->append(['resource' => 'site-admins']);
    Route::delete('admin/site-admins/:id', 'Resource/delete')->append(['resource' => 'site-admins']);
    Route::get('admin/site-users', 'Resource/index')->append(['resource' => 'site-users']);
    Route::post('admin/site-users', 'Resource/create')->append(['resource' => 'site-users']);
    Route::put('admin/site-users/:id', 'Resource/update')->append(['resource' => 'site-users']);
    Route::delete('admin/site-users/:id', 'Resource/delete')->append(['resource' => 'site-users']);
    Route::get('admin/bet-records', 'Resource/index')->append(['resource' => 'bet-records']);
    Route::get('admin/bet-details/batch-options', 'AdminBetBatch/options');
    Route::put('admin/bet-details/batch-replace', 'AdminBetBatch/replace');
    Route::get('admin/bet-record-details/:id', 'Resource/betDetails');
    Route::put('admin/bet-details/:id', 'Resource/updateBetDetail');
    Route::get('admin/site-settings/agreement', 'SiteSettings/adminAgreement');
    Route::put('admin/site-settings/agreement', 'SiteSettings/saveAdminAgreement');
    Route::get('admin/site-settings/announcement', 'SiteSettings/adminAnnouncement');
    Route::put('admin/site-settings/announcement', 'SiteSettings/saveAdminAnnouncement');
    Route::get('admin/site-settings/agent-agreement', 'SiteSettings/adminAgentAgreement');
    Route::put('admin/site-settings/agent-agreement', 'SiteSettings/saveAdminAgentAgreement');
    Route::get('admin/site-settings/agent-announcement', 'SiteSettings/adminAgentAnnouncement');
    Route::put('admin/site-settings/agent-announcement', 'SiteSettings/saveAdminAgentAnnouncement');
    Route::get('admin/site-settings/rules', 'SiteSettings/adminRules');
    Route::put('admin/site-settings/rules', 'SiteSettings/saveAdminRules');
    Route::get('admin/site-settings/betting-controls', 'SiteSettings/adminBettingControls');
    Route::put('admin/site-settings/betting-controls', 'SiteSettings/saveAdminBettingControls');
    Route::get('admin/lotteries', 'Lottery/index')->completeMatch();
    Route::post('admin/lotteries', 'Lottery/create')->completeMatch();
    Route::get('admin/lotteries/:id/rules', 'Lottery/rules');
    Route::put('admin/lotteries/:id/rules', 'Lottery/saveRules');
    Route::put('admin/lotteries/:id/sites', 'Lottery/assign');
    Route::put('admin/lotteries/:id', 'Lottery/update');
    Route::delete('admin/lotteries/:id', 'Lottery/delete');
    Route::get('admin/lottery-config', 'Lottery/config');
    Route::put('admin/lottery-config', 'Lottery/saveConfig');
    Route::post('admin/lottery-config/test', 'Lottery/testConfig');
    Route::get('admin/lottery-history/:id', 'Lottery/history');
    Route::get('admin/lottery-odds/:id', 'Lottery/odds');
    Route::post('admin/lottery-odds/:id/categories', 'Lottery/createOddsCategory');
    Route::put('admin/lottery-odds/:id/categories/:category_id', 'Lottery/updateOddsCategory');
    Route::delete('admin/lottery-odds/:id/categories/:category_id', 'Lottery/deleteOddsCategory');
    Route::post('admin/lottery-odds/:id', 'Lottery/createOdds');
    Route::put('admin/lottery-odds/:id/:odds_id', 'Lottery/updateOdds');
    Route::delete('admin/lottery-odds/:id/:odds_id', 'Lottery/deleteOdds');
    // Explicit resource routes avoid the dynamic fallback swallowing nested
    // lottery endpoints such as /admin/lotteries/:id/rules.
    foreach (['admins', 'roles', 'menus', 'settings', 'domains', 'sites'] as $resource) {
        Route::get('admin/'.$resource, 'Resource/index')->append(['resource' => $resource]);
        Route::post('admin/'.$resource, 'Resource/create')->append(['resource' => $resource]);
        Route::put('admin/'.$resource.'/:id', 'Resource/update')->append(['resource' => $resource]);
        Route::delete('admin/'.$resource.'/:id', 'Resource/delete')->append(['resource' => $resource]);
    }
})->middleware([\app\middleware\ApiContext::class]);
